# Generated by Django 4.2.5 on 2024-12-06 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskill',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserSkill',
        ),
    ]
