# Generated by Django 4.2.5 on 2024-12-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0002_remove_userskill_user_profile_delete_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=100)),
                ('skill_desc', models.TextField()),
                ('skill_btn', models.CharField(max_length=100)),
                ('skill_image', models.ImageField(upload_to='skills/')),
            ],
        ),
    ]
