# Generated by Django 4.2.5 on 2024-12-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0003_skillcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_title', models.CharField(max_length=100)),
                ('feature_desc', models.TextField()),
            ],
        ),
    ]
