# Generated by Django 4.2.5 on 2024-12-06 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0005_skillfeature_feature_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillfeature',
            name='skill_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='Learn.skillcategory'),
        ),
    ]
