# Generated by Django 4.2.5 on 2024-12-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0006_skillfeature_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UloadSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='skills/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
