# Generated by Django 4.2.5 on 2024-12-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0007_uloadskill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UloadSkill',
            new_name='UploadSkill',
        ),
    ]
