# Generated by Django 4.2.5 on 2024-12-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0011_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Skills',
        ),
    ]
