# Generated by Django 4.2.5 on 2024-12-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0012_rename_skill_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='SkilSection',
        ),
    ]
