# Generated by Django 4.2.5 on 2024-12-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0013_rename_skills_skilsection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkilSection',
            new_name='Skill',
        ),
    ]
